### ISSUE TITLE
How can install it?

### ISSUE THREAD

**Issue by colomet** [otacke/h5p-pick-the-symbols#4]
Should I upload from Upload Libraries? at h5p settings page?

**Comment by otacke** [comment]
If you want to use these sources, you'd have to build and pack an h5p library first. But the simplest way is probably to download the demo content at https://www.olivertacke.de/labs/2020/03/06/pick-the-symbols/ and upload it to your system like any other content in the Editor. Missing libraries will be installed if you have sufficient rights.

**Comment by colomet** [comment]
It is a really cool game. It would be really nice to have a variation, instead of the inside of each empty space, if between an empty space with asterisk ( * * ) instead, we can have a variation where words can be used.

**Comment by otacke** [comment]
@colomet It was contract work. If you want further development, please see the readme.
